/* Auto-generated by scripts/sync-news-spreadsheet.js.
   Edit data/news.xlsx and rerun the script. */
(function () {
  window.NEWS_ITEMS = [
    {
      "title": "Lecturer for NN Explainability at the AstroStatistics Summer School held in Rome",
      "link": "https://astrostat-academy.github.io/website-school-7/",
      "date": "26th July 2026"
    }
  ];
})();
