/* Auto-generated by scripts/sync-news-spreadsheet.js.
   Edit data/news.xlsx while scripts/watch-news-spreadsheet.js is running. */
(function () {
  window.NEWS_ITEMS = [
    {
      "title": "Contributing a talk on sparsity/statistics-informed machine learning for inverse problems at the Physics-Informed Machine Learning Workshop at FORTH",
      "link": "https://www.grss-ieee.org/event/workshop-on-physics-informed-machine-learning/",
      "date": "16th September"
    },
    {
      "title": "Gave a lecture on NN Explainability at the AstroStatistics Summer School held in Rome",
      "link": "https://astrostat-academy.github.io/website-school-7/",
      "date": "26th July 2026"
    }
  ];
})();
